import { Download, FileText } from "lucide-react";

interface ReportExportProps {
  record: any;
  patientName?: string;
  userRole: string;
}

export const ReportExport = ({ record, patientName, userRole }: ReportExportProps) => {
  const generateReport = () => {
    const now = new Date().toLocaleString();
    const vitals = record.clinicalData?.vitals || {};
    const symptoms = record.clinicalData?.symptoms || [];
    const prescriptions = record.prescriptions || [];
    const prediction = record.prediction || {};
    const conditions = prediction.predicted_conditions || [];

    let report = `
╔══════════════════════════════════════════════════════════════╗
║               SECURE EHR SYSTEM — MEDICAL REPORT            ║
║              Blockchain-Verified Electronic Record           ║
╚══════════════════════════════════════════════════════════════╝

Generated: ${now}
Report Type: Comprehensive Cardiovascular Assessment
Blockchain TX: ${record.blockchainTxHash || 'N/A'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━
Patient: ${patientName || 'N/A'}
Wallet Address: ${record.patientAddress || 'N/A'}
Record Created: ${new Date(record.createdAt).toLocaleDateString()}
Last Modified: ${new Date(record.lastModified).toLocaleDateString()}
Primary Physician: ${record.primaryDoctorId || 'N/A'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VITAL SIGNS
━━━━━━━━━━━
Blood Pressure:  ${vitals.bp || 'N/A'} mmHg
Heart Rate:      ${vitals.heartRate || 'N/A'} bpm
Cholesterol:     ${vitals.cholesterol || 'N/A'} mg/dL
Blood Sugar:     ${vitals.sugarLevel || 'N/A'} mg/dL

REPORTED SYMPTOMS
━━━━━━━━━━━━━━━━━
${symptoms.length > 0 ? symptoms.map((s: string, i: number) => `  ${i + 1}. ${s}`).join('\n') : '  No symptoms reported'}
`;

    // AI section only for Doctor/Admin
    if (userRole === "Doctor" || userRole === "Admin") {
      report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AI RISK ASSESSMENT (XGBoost ML Model + Gemini AI)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Overall Risk Level: ${prediction.riskLevel || 'N/A'}
Risk Probability:   ${prediction.xgboostRisk ? (prediction.xgboostRisk * 100).toFixed(1) + '%' : 'N/A'}
Model Confidence:   ${prediction.xgboostConfidence ? (prediction.xgboostConfidence * 100).toFixed(1) + '%' : 'N/A'}

PRIMARY DIAGNOSIS: ${prediction.recommendation || 'N/A'}

DETECTED CARDIOVASCULAR CONDITIONS:
${conditions.length > 0
  ? conditions.map((c: any, i: number) =>
    `  ${i + 1}. ${c.name}\n     Probability: ${c.probability}% | Severity: ${c.severity}`
  ).join('\n')
  : '  No conditions detected'}

CLINICAL RECOMMENDATIONS:
${prediction.clinical_recommendations || '  N/A'}

GEMINI AI CLINICAL SUMMARY:
${prediction.summary || '  N/A'}
`;
    }

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRESCRIPTIONS (${prescriptions.length})
━━━━━━━━━━━━━
${prescriptions.length > 0
  ? prescriptions.map((p: any, i: number) =>
    `  ${i + 1}. ${p.medicineName || 'N/A'}
     Dosage: ${p.dosage || 'N/A'}
     Duration: ${p.duration || 'N/A'}
     Frequency: ${p.frequency || 'N/A'}
     Timing: ${p.timing || 'N/A'}
     Instructions: ${p.instructions || 'N/A'}
     Prescribed by: ${p.prescribedBy?.slice(0, 8)}...${p.prescribedBy?.slice(-4) || 'N/A'}
     Date: ${p.prescribedDate ? new Date(p.prescribedDate).toLocaleDateString() : 'N/A'}`
  ).join('\n\n')
  : '  No prescriptions on file'}

DOCTOR RECOMMENDATIONS:
${record.doctorRecommendations || '  N/A'}

${record.patientNotes ? `PATIENT NOTES:\n${record.patientNotes}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BLOCKCHAIN VERIFICATION
━━━━━━━━━━━━━━━━━━━━━━━
Transaction Hash: ${record.blockchainTxHash || 'N/A'}
Record ID:        ${record._id || 'N/A'}
Network:          Ethereum Mainnet (Chain ID: 1)
Status:           Confirmed & Immutable

UPDATE HISTORY:
${(record.updateHistory || []).map((u: any, i: number) =>
  `  ${i + 1}. [${new Date(u.timestamp).toLocaleString()}] ${u.action} by ${u.updatedByRole}
     TX: ${u.txHash || 'N/A'}
     ${u.description}`
).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by the Secure EHR System.
All records are verified on the Ethereum blockchain.
Powered by XGBoost ML & Google Gemini AI.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    // Download as text file
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `EHR_Report_${record.patientAddress?.slice(0, 8) || 'unknown'}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!record) return null;

  return (
    <button
      onClick={generateReport}
      className="px-3 py-2 bg-zinc-800 border border-zinc-700 text-zinc-400 hover:text-white hover:border-zinc-500 rounded-xl flex items-center gap-2 transition-all font-black text-[10px] uppercase tracking-wider"
      title="Download medical report"
    >
      <Download size={14} />
      Export Report
    </button>
  );
};
